language: generic
sudo:     false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

env:
  - IC_PYTHON_VERSION=3.7

os:
  - linux
  - osx

branches:
  except:
    - /^docs\..*$/
    - reco_city

install:
  - source manage.sh work_in_python_version_no_tests ${IC_PYTHON_VERSION}

script:
  - HYPOTHESIS_PROFILE=travis-ci bash manage.sh run_tests_par


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install git-lfs; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then git lfs install;      fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then git lfs pull; fi
